### ISSUE TITLE
html5lib bug

### ISSUE THREAD

**Issue by kuntzer** [vbonvin/POUET#29]
With the current version of the html5lib (html5lib 1.0.1), I get an error when trying to load the finding chart:

	Traceback (most recent call last):
	  File "main.py", line 334, in doubleclik_list
	    skychart.show()
	  File "main.py", line 1721, in show
	    ax = plots.plot_target_on_sky(self.target, figure=self.figure, northisup=self.northisup, eastisright=self.eastisright, boxsize=self.boxsize, survey=self.survey, cmap=self.cmap)
	  File "/home/kuntzer/workspace/ObsScheduler/pouet/plots.py", line 271, in plot_target_on_sky
	    from astroquery.skyview import SkyView
	  File "/usr/local/lib/python3.5/dist-packages/astroquery/skyview/__init__.py", line 16, in <module>
	    from .core import SkyView, SkyViewClass
	  File "/usr/local/lib/python3.5/dist-packages/astroquery/skyview/core.py", line 3, in <module>
	    from bs4 import BeautifulSoup
	  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
	    from .builder import builder_registry, ParserRejectedMarkup
	  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
	    from . import _html5lib
	  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
	    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
	AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
	
I found a workaround for now (see [that post](https://www.bountysource.com/issues/51519225-module-html5lib-treebuilders-has-no-attribute-_base)): downgrade html5lib to version 1.0b8.

    sudo pip install --upgrade html5lib==1.0b8

Note that this is most likely temporary. 

I will check that behaviour regularly.

**Comment by vbonvin** [comment]
Any news on this? Shall we keep the issue open but added to another milestone (or no milestone at all)?

**Comment by kuntzer** [comment]
I've upgraded:

* html5lib back to 1.0.1
* astroquery
* BeautifulSoup

It seems that the bug has been resolved. I don't see a mention of html5lib or BeautifulSoup in the requirements, so I close this issue.
